name: Go

env:
  GIN_MODE: release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      checks: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5   # ‚Üê current version in 2026
      with:
        go-version: '1.23'      # or '1.22', '1.21', or 'stable'
        cache: true

    - name: Revive Action
      uses: morphy2k/revive-action@v2.4.1

    - name: Run staticcheck
      uses: dominikh/staticcheck-action@v1.3.0

    - name: Build
      run: |
        go mod download
        go install gotest.tools/gotestsum@latest

    - name: Test
      run: |
        gotestsum --format=standard-verbose --junitfile=junit.xml

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: success() || failure() # always run even if the previous step fails
      with:
        report_paths: '**/junit.xml'
        detailed_summary: true
        include_passed: true
